# Generated by Django 5.1.2 on 2024-11-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('mac', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField()),
                ('upload_speed', models.FloatField()),
                ('ping', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('url', models.URLField()),
                ('tag', models.CharField(default='Default', max_length=100)),
                ('mac', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('monitor_all', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('latency', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.website')),
            ],
        ),
    ]
