services:
  # mysql:
  #   image: mysql:8.0
  #   container_name: mysql_db
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_DATABASE: netalert
  #     MYSQL_USER: netalert_user
  #     MYSQL_PASSWORD: netalert_password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:3060
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3060:3060"
    network_mode: host
    # depends_on:
    #   - mysql
    # environment:
    #   MYSQL_HOST: mysql
    #   MYSQL_PORT: 3306
    #   MYSQL_DATABASE: your_database_name
    #   MYSQL_USER: your_db_user
    #   MYSQL_PASSWORD: your_db_password

  frontend:
    build: ./frontend
    container_name: react_frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - backend
  #     - frontend

volumes:
  mysql_data:
